apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-prod
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml
