apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake-store
spec:
  provider:
    fake:
      data:
        - key: db/password
          value: "supersecret-v2"
          version: "v1"
        - key: db/username
          value: "admin"
          version: "v1"
