apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: db-credentials      # Name des Kubernetes-Secrets, das entsteht
    creationPolicy: Owner     # Bei Löschen der ExternalSecret-CR wird auch das Secret gelöscht
  data:
    - secretKey: password     # Key im resultierenden K8s-Secret
      remoteRef:
        key: db/password      # Key im Fake-Store
    - secretKey: username
      remoteRef:
        key: db/username
