apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: db/password
        version: v1
    - secretKey: username
      remoteRef:
        key: db/username
        version: v1
